php artisan make:seeder FavoriteSeeder
php artisan db:seed --class=FavoriteSeeder
php artisan make:seeder PostsSeeder
php artisan db:seed --class=PostsSeeder
php artisan make:seeder ProfileSeeder
php artisan db:seed --class=ProfileSeeder
php artisan make:seeder UserFavoriteSeeder
php artisan db:seed --class=UserFavoriteSeeder
php artisan make:seeder UserSeeder
php artisan db:seed --class=UserSeeder